name: Update READMEs with terraform-docs on Merge

on:
  push:
    branches:
      - master
    paths:
      - modules/**/*.tf
      - templates/**/*.tf

permissions:
  contents: write

jobs:
  detect-changes:
    name: Detect Modified Directories
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get_dirs.outputs.dirs }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed Terraform directories
        id: gat_dirs
        shell: bash
        run: |
          BEFORE_COMMIT="${{ github.event.before || 'HEAD~1' }}"
          CHANGED=$(git diff --name-only "$BEFORE_COMMIT" "${{ github.sha }}" \
            | grep -E '^(modules|templates)/.*\.tf$' \
            | xargs -n1 dirname \
            | sort -u)
          echo "Changed directories:"
          echo "$CHANGED"
          if [ -z "$CHANGED" ]; then
            echo "dirs=[]" >> "$GITHUB_OUTPUT"
          else
            DIRS_JSON=$(echo "$CHANGED" | jq -R . | jq -s -c .)
            echo "dirs=$DIRS_JSON" >> "$GITHUB_OUTPUT"
          fi

  update-readmes:
    name: Update README.md with terraform-docs
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.dirs != '[]' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-changes.outputs.dirs) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract ticket ID from last commit
        id: ticket
        shell: bash
        run: |
          TICKET=$(git log -1 --pretty=%B | grep -oE 'NCP-[0-9]+' || echo "NCP-XXXX")
          echo "ticket=$TICKET" >> "$GITHUB_OUTPUT"

      - name: Check if README.md exists
        id: readme
        shell: bash
        run: |
          if [ -f "${{ matrix.dir }}/README.md" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run terraform-docs
        if: ${{ steps.readme.outputs.exists == 'true' }}
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ${{ matrix.dir }}
          output-file: README.md
          output-method: inject
          git-push: false

      - name: Fix Git permissions
        shell: bash
        run: |
          sudo chown -R "$(whoami)":"$(whoami)" .git/

      - name: Commit README.md update
        if: ${{ steps.readme.outputs.exists == 'true' }}
        shell: bash
        run: |
          git config user.name "tester"
          git config user.email "tester@users.noreply.github.com"
          git add "${{ matrix.dir }}/README.md"
          git commit -m "${{ steps.ticket.outputs.ticket }}: Auto-update README.md with terraform-docs" || echo "No changes to commit"

      - name: Pull with rebase and push changes
        if: ${{ steps.readme.outputs.exists == 'true' }}
        shell: bash
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          git pull origin "$BRANCH"
          git push origin "$BRANCH"
